# Generated by Django 5.2.8 on 2025-11-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('legal_rep', models.ManyToManyField(related_name='student', to='family.legalrep')),
            ],
        ),
    ]
