# Generated by Django 5.2.8 on 2026-01-17 01:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Estudante',
                'verbose_name_plural': 'Estudantes',
            },
        ),
        migrations.CreateModel(
            name='LegalRepStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_rep_type', models.CharField(choices=[('Pai', 'Pai'), ('Mãe', 'Mãe'), ('Avô', 'Avô'), ('Avó', 'Avó'), ('Tio', 'Tio'), ('Tia', 'Tia'), ('Irmão', 'Irmão'), ('Irmã', 'Irmã'), ('Amigo da família', 'Amigo da família'), ('Parente de 3º grau', 'Parente de 3º grau'), ('Responsável legal', 'Responsável legal'), ('Outro', 'Outro')], max_length=100)),
                ('legal_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legalrepstudent', to='family.legalrep')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legalrepstudent', to='student.student')),
            ],
            options={
                'verbose_name': 'Responsável Legal do Estudante',
                'verbose_name_plural': 'Responsáveis Legais dos Estudantes',
            },
        ),
    ]
